// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPdFv68PC85ZUoUexflrqk6Ub0KdtXSOU',
    appId: '1:194192825554:web:4d7c03c4c0685eba9b210b',
    messagingSenderId: '194192825554',
    projectId: 'suittailorapp',
    authDomain: 'suittailorapp.firebaseapp.com',
    databaseURL: 'https://suittailorapp-default-rtdb.firebaseio.com',
    storageBucket: 'suittailorapp.firebasestorage.app',
    measurementId: 'G-XJT02PF717',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCOkyL8Tq5lFMH5DQ0TsM3S-7LBZG8m1c',
    appId: '1:194192825554:android:fc92f52e393b47a49b210b',
    messagingSenderId: '194192825554',
    projectId: 'suittailorapp',
    databaseURL: 'https://suittailorapp-default-rtdb.firebaseio.com',
    storageBucket: 'suittailorapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmX7KZpu1YAYDjY84daBj7og34b_hVQU',
    appId: '1:194192825554:ios:b9590c01e13036769b210b',
    messagingSenderId: '194192825554',
    projectId: 'suittailorapp',
    databaseURL: 'https://suittailorapp-default-rtdb.firebaseio.com',
    storageBucket: 'suittailorapp.firebasestorage.app',
    iosBundleId: 'com.example.tailorApp',
  );

  static const FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyAXmX7KZpu1YAYDjY84daBj7og34b_hVQU',
    appId: '1:194192825554:ios:b9590c01e13036769b210b',
    messagingSenderId: '194192825554',
    projectId: 'suittailorapp',
    databaseURL: 'https://suittailorapp-default-rtdb.firebaseio.com',
    storageBucket: 'suittailorapp.firebasestorage.app',
    iosBundleId: 'com.example.tailorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPdFv68PC85ZUoUexflrqk6Ub0KdtXSOU',
    appId: '1:194192825554:web:4d7c03c4c0685eba9b210b',
    messagingSenderId: '194192825554',
    projectId: 'suittailorapp',
    authDomain: 'suittailorapp.firebaseapp.com',
    databaseURL: 'https://suittailorapp-default-rtdb.firebaseio.com',
    storageBucket: 'suittailorapp.firebasestorage.app',
    measurementId: 'G-XJT02PF717',
  );
}
